use crate::azure::client::AzureDevOpsClient;
use rmcp::{
    handler::server::router::tool::ToolRouter,
    model::{Implementation, ServerCapabilities, ServerInfo},
    tool_handler,
};
use std::sync::Arc;

#[derive(Clone)]
pub struct AzureMcpServer {
    client: Arc<AzureDevOpsClient>,
    tool_router: ToolRouter<Self>,
}

// Tool router implementation is auto-generated by build.rs
// The build script scans src/mcp/tools for #[mcp_tool] attributes
// and generates the impl block in target/debug/build/.../out/generated_tools.rs
include!(concat!(env!("OUT_DIR"), "/generated_tools.rs"));

#[tool_handler]
impl rmcp::ServerHandler for AzureMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            server_info: Implementation {
                name: env!("CARGO_PKG_NAME").into(),
                version: env!("CARGO_PKG_VERSION").into(),
                icons: None,
                title: None,
                website_url: Some(env!("CARGO_PKG_HOMEPAGE").into()),
            },
            instructions: Some(
                "Use this tool to interact with Azure DevOps Boards and Work Items".into(),
            ),
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            ..Default::default()
        }
    }
}
