use crate::azure::api_trait::AzureDevOpsApi;
use crate::azure::client::AzureDevOpsClient;
use rmcp::{
    handler::server::router::tool::ToolRouter,
    model::{Implementation, ServerCapabilities, ServerInfo},
    tool_handler,
};
use std::sync::Arc;

#[derive(Clone)]
pub struct AzureMcpServer {
    client: Arc<dyn AzureDevOpsApi + Send + Sync>,
    tool_router: ToolRouter<Self>,
}

// Tool router implementation is auto-generated by build.rs
// The build script scans src/mcp/tools for #[mcp_tool] attributes
// and generates the impl block in target/debug/build/.../out/generated_tools.rs
include!(concat!(env!("OUT_DIR"), "/generated_tools.rs"));

#[tool_handler(router = self.tool_router)]
impl rmcp::ServerHandler for AzureMcpServer {
    fn get_info(&self) -> ServerInfo {
        // ServerInfo (InitializeResult) and Implementation are #[non_exhaustive]
        // in rmcp 2.x, so they cannot be built with a struct literal. Start from
        // Default and set the fields we care about.
        let mut info = ServerInfo::default();
        info.server_info = Implementation::new(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION"))
            .with_website_url(env!("CARGO_PKG_HOMEPAGE"));
        info.instructions =
            Some("Use this tool to interact with Azure DevOps Boards and Work Items".into());
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info
    }
}
