name: CI - PR - Build & Test

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build & Test - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Windows-x86_64
            runs-on: windows-latest

          - os-name: Linux-x86_64
            runs-on: ubuntu-latest

          - os-name: macOS-aarch64
            runs-on: macos-14

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Build
        run: cargo build --release --locked

      - name: Clippy
        run: cargo clippy --features test-support --locked -- -D warnings

      - name: Test
        run: cargo test --release --locked --features test-support

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build E2E Docker images
        run: make test-e2e-build

      - name: Run E2E tests
        run: cargo test --features test-support,e2e-tests --locked

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Security audit
        run: cargo audit

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
